name: TurbGen_py27

channels:
  - nodefaults

dependencies:
  - python=2.7
  - numpy
  - matplotlib=2.2
  - gcc  # This includes gfortran
  - h5py
# # For building docs:
#  - sphinx
#  - numpydoc
# # Testing:
#  - pytest
# # Interactive
#  - ipython=4.2